name: enhanced_change_notifier
description: A enhanced version of ChangeNotifier introduces new features `target`, `once`, and `immediate`.
homepage: https://github.com/leo1394/enhanced_change_notifier
repository: https://github.com/leo1394/enhanced_change_notifier
issue_tracker: https://github.com/leo1394/enhanced_change_notifier/issues
version: 0.2.1
environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

topics:
  - change-notifier
  - property-notifier
  - once
  - immediate